---
sudo: required

services:
  - docker

env:
  - VERSION=1.8.43

install:
  - docker build -t lgatica/dpl:$VERSION -t lgatica/dpl:latest .

script:
  - docker run --rm --entrypoint sh lgatica/dpl:latest -c 'if [ -e /usr/bin/dpl ]; then echo $DPL_VERSION; else exit 1; fi'

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push lgatica/dpl:$VERSION
  - docker push lgatica/dpl:latest

notifications:
  email: false
